project_name: 理想测试项目名称

env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
tester_name: 理想

# 域名1
host: https://www.wanandroid.com
# 域名2，支持多个域名配置
app_host:
mes_host: http://192.168.202.172

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: True

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 1
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False

# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置

# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=32d9d360f98faeb991a53f8b084eaf2e5ed328b0561400092bdeff8ecc8f5a5d
#  secret: SECdea6489dfcc3b9259da943c5ae38d3530696f2fa83ac72a9ee716e9511675b9b
#  webhook:
  secret: SECbc5902f765e80da5b0e42cb26cb3fd0c9786505aa3fa4aec718d4ee8a3f0af0c
# 数据库相关配置
mysql_db:
  # 数据库开关
  switch: False
  host: localhost
  user: root
  password: '123456789'
  port: 3306

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
wechat:
  webhook:


### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知
email:
  send_user: 1603453211@qq.com
  email_host: smtp.qq.com
  # 自己到QQ邮箱中配置stamp_key
  stamp_key: rzuabbobadbuhadc
  # 收件人改成自己的邮箱
  send_list: 531808264@qq.com

# 飞书通知
lark:
  webhook:



